# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]

# GAZEBO SINGLE TAG NOISE TEST
# tag_bundles:
#   [
#   {
#   name: 'single',
#   layout:
#     [
#     {id: 5, size: 0.4}
#     ]
#   }
#   ]

# GAZEBO BUNDLE EFFECT ON NOISE TEST
# tag_bundles:
#   [
#   {
#   name: 'bundle_1',
#   layout:
#     [
#     {id: 8, size: 0.15}
#     ]
#   },
#   {
#   name: 'bundle_3',
#   layout:
#     [
#     {id: 8, size: 0.15},
#     {id: 7, size: 0.15, x: -0.16875},
#     {id: 9, size: 0.15, x: 0.16875},
#     ]
#   },
#   {
#   name: 'bundle_5',
#   layout:
#     [
#     {id: 8, size: 0.15},
#     {id: 7, size: 0.15, x: -0.16875},
#     {id: 9, size: 0.15, x: 0.16875},
#     {id: 5, size: 0.15, y: 0.16875},
#     {id: 11, size: 0.15, y: -0.16875}
#     ]
#   },
#   {
#   name: 'bundle_9',
#   layout:
#     [
#     {id: 8, size: 0.15},
#     {id: 7, size: 0.15, x: -0.16875},
#     {id: 9, size: 0.15, x: 0.16875},
#     {id: 5, size: 0.15, y: 0.16875},
#     {id: 11, size: 0.15, y: -0.16875},
#     {id: 4, size: 0.15, x: -0.16875, y: 0.16875},
#     {id: 6, size: 0.15, x: 0.16875, y: 0.16875},
#     {id: 10, size: 0.15, x: -0.16875, y: -0.16875},
#     {id: 12, size: 0.15, x: 0.16875, y: -0.16875}
#     ]
#   }
#   ]


# GREEN FOAM BLOCK PATTERN
# tag_bundles:
#   [
#     {
#       name: 'charging_pad',
#       layout:
#         [
#           {id: 9,  size: 0.1},
#           {id: 2,  size: 0.1, x: -0.05625, y:  0.1125},
#           {id: 13, size: 0.1, x:  0.05625, y:  0.1125},
#           {id: 0,  size: 0.1, x: -0.05625, y: -0.1125},
#           {id: 4,  size: 0.1, x:  0.05625, y: -0.1125}
#         ]
#     }
#   ]


# SKYSENSE USED CHARGING PAD PATTERN
tag_bundles:
  [
    {
      name: 'charging_pad',
      layout:
        [
          {id: 5,  size: 0.15, x: -0.25, y: 0.5517, z: 0.0, qw: 1.0,    qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 11, size: 0.15, x: 0.0,   y: 0.5517, z: 0.0, qw: 1.0,    qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 16, size: 0.15, x: 0.25,  y: 0.5517, z: 0.0, qw: 1.0,    qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 25, size: 0.48, x: 0.0,   y: 0.9517, z: 0.0, qw: 0.7071, qx: 0.0, qy: 0.0, qz: 0.7071}
        ]
    }
  ]

# SKYSENSE PROPOSED ALTERNATIVE CHARGING PAD PATTERN
# tag_bundles:
#   [
#   {
#   name: 'charging_pad',
#   layout:
#     [
#     # Panel along +y
#     {id: 5,  size: 0.15, x: -0.25, y: 0.5517, z: 0.0, qw: 1.0,    qx: 0.0, qy: 0.0, qz: 0.0},
#     {id: 11, size: 0.15, x: 0.0,   y: 0.5517, z: 0.0, qw: 1.0,    qx: 0.0, qy: 0.0, qz: 0.0},
#     {id: 16, size: 0.15, x: 0.25,  y: 0.5517, z: 0.0, qw: 1.0,    qx: 0.0, qy: 0.0, qz: 0.0},
#     {id: 25, size: 0.48, x: 0.0,   y: 0.9517, z: 0.0, qw: 0.7071, qx: 0.0, qy: 0.0, qz: 0.7071},
#     # Panel along -x
#     {id: 12, size: 0.15, x: -0.5517, y: 0.25, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#     {id: 13, size: 0.15, x: -0.5517, y: 0.0, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#     {id: 14, size: 0.15, x: -0.5517, y: -0.25, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#     {id: 15, size: 0.48, x: -0.9517, y: 0.0, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#     # Panel along -y
#     {id: 8, size: 0.15, x: -0.25, y: -0.5517, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#     {id: 7, size: 0.15, x: 0.0, y: -0.5517, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#     {id: 6, size: 0.15, x: 0.25, y: -0.5517, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#     {id: 9, size: 0.48, x: 0.0, y: -0.9517, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#     # Panel along +x
#     {id: 1, size: 0.15, x: 0.5517, y: 0.25, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#     {id: 2, size: 0.15, x: 0.5517, y: 0.0, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#     {id: 3, size: 0.15, x: 0.5517, y: -0.25, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#     {id: 4, size: 0.48, x: 0.9517, y: 0.0, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
#     ]
#   }
#   ]
